name: Conda

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-18.04, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    runs-on: ${{ matrix.platform }}

    # The setup-miniconda action needs this to activate miniconda
    defaults:
      run:
        shell: "bash -l {0}"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache conda
        uses: actions/cache@v1
        with:
          path: ~/conda_pkgs_dir
          key: ${{matrix.os}}-conda-pkgs-${{hashFiles('**/conda/meta.yaml')}}

      - name: Get conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: strict
          use-only-tar-bz2: true
          auto-activate-base: true

      - name: Prepare
        run: conda install conda-build conda-verify

      - name: Build
        run: conda build conda

      - name: Install
        run: conda install -c ${CONDA_PREFIX}/conda-bld/ pystache

      - name: Test
        run: python test_pystache.py
